name: Building TWRP TESTA11

on:
  workflow_dispatch:
    inputs:
        tagName:
            description: 'tagName'     
            required: true
            default: ''
        tagBody:
            description: 'tagBody'     
            required: true
            default: ''

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  MANIFEST_BRANCH: twrp-11
  DEVICE: Armor8Pro
  DT_REPO: https://github.com/lopestom/device_ulefone_Armor8Pro.git
  DT_PATH: device/ulefone/Armor8Pro
  TARGET: recovery

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main
         
       - name: Initializing environment
         run: |
            export DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8 JAVA_OPTS=" -Xmx7G " JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
            sudo apt-get -qqy update &>/dev/null
            sudo apt-get -qqy install --no-install-recommends lsb-core lsb-security patchutils bc android-sdk-platform-tools adb fastboot openjdk-8-jdk ca-certificates-java maven python-all-dev python-is-python2 lzip lzop xzdec pixz libzstd-dev lib32z1-dev exfat-utils exfat-fuse gcc gcc-multilib g++-multilib clang llvm lld cmake ninja-build libxml2-utils xsltproc expat re2c libxml2-utils xsltproc expat re2c libreadline-gplv2-dev libsdl1.2-dev libtinfo5 xterm rename schedtool bison gperf libb2-dev pngcrush imagemagick optipng advancecomp &>/dev/null
            sudo apt-get -qqy purge default-jre-headless openjdk-11-jre-headless &>/dev/null
            sudo apt-get -qy clean &>/dev/null && sudo apt-get -qy autoremove &>/dev/null
            sudo rm -rf -- /var/lib/apt/lists/* /var/cache/apt/archives/* &>/dev/null
            git config --global user.name "lopestom"
            git config --global user.email "lopestom1@gmail.com"    
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery and device tree sources
         run: |
             repo init --depth=1 -u $MANIFEST -b $MANIFEST_BRANCH
             repo sync -f --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
             git clone $DT_REPO --depth=1 $DT_PATH
             
       - name: Build
         run: |
              . build/envsetup.sh
              lunch twrp_$DEVICE-eng || true
              export ALLOW_MISSING_DEPENDENCIES=true && mka ${TARGET}image
              echo "CODENAME=${CODENAME}" >> ${GITHUB_ENV}
              echo "BuildPath=/home/runner/builder" >> ${GITHUB_ENV}
              
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.ARMOR }}
         with:
           tag_name: ${{ github.event.inputs.tagName }}
           release_name: Release ${{ github.event.inputs.tagName }}
           body: ${{ github.event.inputs.tagBody }}
           draft: false
           prerelease: false
           
       - name: Upload Release Asset
         id: upload-release-asset 
         uses: xresloader/upload-to-github-release@master
         env:
           GITHUB_TOKEN: ${{ secrets.ARMOR }}
         with:
           file: "${BuildPath}/out/target/product/${CODENAME}/{recovery.img,*.zip}"
           release_id: ${{ steps.create_release.outputs.id }}
           overwrite: true
           verbose: true
           draft: false
